### ISSUE TITLE
Some question about forgetting_events

### ISSUE THREAD

**Issue by Muran337287** [stanford-futuredata/selection-via-proxy#1]
When using forgetting_events as selection method, if the training of proxy model is interrupted, do you need to record the status of forgetting_events?

**Comment by codyaustun** [comment]
What do you mean by "interrupted"? If you're training for fewer epochs or using a precomputed ranking, forgetting_events should just work. If you mean training is killed and you want to resume, you would need to save the state of forgetting events.

**Comment by Muran337287** [comment]
Ok！ Thank you for your reply!
