### ISSUE TITLE
Embeddings vs Activations

### ISSUE THREAD

**Issue by diff7** [stanford-futuredata/selection-via-proxy#3]
Hi, thank you for a really interesting repo. 

I was curious would it be the same for K-centers if we use embedding  instead of activations? 

Also, did you test only preact resnets or resnet18 would be as good as preact resnet for K-centers?

Thanks!

**Comment by diff7** [comment]
Should be the same

**Comment by codyaustun** [comment]
Thanks for the question @diff7! It looks like you figured it out, but if you have any further questions let me know.

**Comment by diff7** [comment]
Cool, thank you!
