### ISSUE TITLE
There is seems to be no difference  between random & k-centers CIFAR10 preact 20

### ISSUE THREAD

**Issue by diff7** [stanford-futuredata/selection-via-proxy#4]
Hi, 
I am getting exactly the same results for k-centers & random coresets with preact20 on cifar10. 

I used preact20 as a target and proxy. 

Maybe you have changed something in the code after all the experiments.

**Comment by codyaustun** [comment]
Can you send the command lines you used and, if possible, the results you got? It is hard to debug without knowing exactly what you did.

**Comment by diff7** [comment]
Hi, thank you for your reply!

**Comment by diff7** [comment]
Hi, thank you for your reply!

Below is random and k-centers on the top. (from target/results.csv)
I believe it should work and I want it to work but unfortunately it does not.
I used these commands.

python3 -m svp.cifar coreset --dataset cifar10 --arch preact20 --num-workers 4     --subset 10000 --selection-method kcenters

python3 -m svp.cifar coreset --dataset cifar10 --arch preact20 --num-workers 4     --subset 10000 --selection-method random

![image](https://user-images.githubusercontent.com/34035501/108252346-92015e00-7169-11eb-8637-218d897c2fe5.png)


Also, I did not install packages from the requirements but it should not be the problem.

Let me know if you need any other information.

**Comment by codyaustun** [comment]
@diff7 thanks for providing the command line and the screenshots. Two things come to mind.

1) I haven't run the command with --subset 10000 before. The smallest I have done is 15000 so maybe there are too few examples for kcenters to make a difference. I am running your commands now to double-check. I'll follow up once the experiments are done.

2) The first screenshot only goes to epoch 99, while the second goes all the way to epoch 181 (the default). Did you let both commands finish before comparing the results? kcenters is much slower than random sampling, so you might have checked too soon.

**Comment by diff7** [comment]
Hi, thank you for your reply!

I am really sorry, indeed I was looking at the wrong numbers. Now I am getting better results.

However, I use only 100 epochs.

![image](https://user-images.githubusercontent.com/34035501/109062103-8a593080-76f8-11eb-988c-a1e19d82c6f6.png)

Also, I was looking at your results and they look better. 
![image](https://user-images.githubusercontent.com/34035501/109062747-5cc0b700-76f9-11eb-8a7b-4ce6579a58da.png)

Do you think it's possible that such  difference comes from number of epochs?  I'll probably check it, I am still curious. ))
Also, forgetting works pretty well on 100 epochs.

**Comment by codyaustun** [comment]
Great! That looks more like it. 

What do you mean by the difference? The gap between random sampling and the greedy k-centers approach looks reasonable from a glance. It is hard to tell exactly because the y-axis is different. Both methods are achieving lower accuracy, but that is probably because you're running for half of the learning rate schedule. Also, I don't see error bars on the random sampling line, so the point at 35,000 (i.e., 70% of the data) might just be a lucky run. The accuracy even goes down when you get to 80%

**Comment by diff7** [comment]
Hi, got it! 

Thank you  very much for support and your time!

I am closing the issue.
